<?php

namespace PressGang\Bosun\Agents;

/**
 * The agent files bosun writes the composed guidelines to.
 *
 * Never clobbers a hand-written file: a target is only overwritten when it
 * carries the bosun marker (or doesn't exist, or $force is set). Kept as a
 * simple map for now; if per-agent formats diverge, promote entries to
 * target classes.
 */
class AgentTargets {

	/**
	 * The marker identifying a bosun-generated file (present in the composed
	 * document's header).
	 */
	public const MARKER = 'composed by pressgang-bosun';

	/**
	 * Agent key => guidelines filename relative to the theme root.
	 *
	 * @var array<string, string>
	 */
	public const TARGETS = [
		'claude' => 'CLAUDE.md',
		'agents' => 'AGENTS.md',
	];

	/**
	 * Writes the composed document to each selected agent target.
	 *
	 * @param string             $theme_dir Absolute path to the child theme.
	 * @param string             $document  Composed guidelines document.
	 * @param array<int, string> $agents    Agent keys to write (defaults to all).
	 * @param bool               $force     Overwrite files without the bosun marker.
	 *
	 * @return array{written: array<int, string>, skipped: array<int, string>}
	 */
	public static function write( string $theme_dir, string $document, array $agents = [], bool $force = false ): array {

		$written = [];
		$skipped = [];
		$agents  = $agents ?: array_keys( self::TARGETS );

		foreach ( $agents as $agent ) {
			if ( ! isset( self::TARGETS[ $agent ] ) ) {
				continue;
			}

			$path = "{$theme_dir}/" . self::TARGETS[ $agent ];

			if ( ! $force && ! self::is_writable_target( $path ) ) {
				$skipped[] = $path;

				continue;
			}

			if ( file_put_contents( $path, $document ) !== false ) {
				$written[] = $path;
			}
		}

		return [ 'written' => $written, 'skipped' => $skipped ];
	}

	/**
	 * Whether a target may be overwritten: it doesn't exist, or it was
	 * generated by bosun (carries the marker).
	 *
	 * @param string $path Absolute file path.
	 *
	 * @return bool
	 */
	protected static function is_writable_target( string $path ): bool {

		if ( ! file_exists( $path ) ) {
			return true;
		}

		return str_contains( (string) file_get_contents( $path ), self::MARKER );
	}
}
